/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';var k=require("@lexical/react/LexicalComposerContext"),v=require("@lexical/utils"),y=require("lexical"),z=require("react"),A="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement?z.useLayoutEffect:z.useEffect;class B{constructor(c){this.key=c;this.ref={current:null};this.setRefElement=this.setRefElement.bind(this)}setRefElement(c){this.ref={current:c}}}
let C=c=>{const a=document.getElementById("typeahead-menu");if(a){var d=a.getBoundingClientRect();d.top+d.height>window.innerHeight&&a.scrollIntoView({block:"center"});0>d.top&&a.scrollIntoView({block:"center"});c.scrollIntoView({block:"nearest"})}};
function D(c){var a=y.$getSelection();if(!y.$isRangeSelection(a)||!a.isCollapsed())return null;var d=a.anchor;if("text"!==d.type)return null;a=d.getNode();if(!a.isSimpleText())return null;d=d.offset;let l=a.getTextContent().slice(0,d);var f=c.matchingString;c=c.replaceableString.length;for(let r=c;r<=f.length;r++)l.substr(-r)===f.substr(0,r)&&(c=r);c=d-c;if(0>c)return null;let n;0===c?[n]=a.splitText(d):[,n]=a.splitText(c,d);return n}
function E(c,a){let d=getComputedStyle(c),l="absolute"===d.position;a=a?/(auto|scroll|hidden)/:/(auto|scroll)/;if("fixed"===d.position)return document.body;for(;c=c.parentElement;)if(d=getComputedStyle(c),(!l||"static"!==d.position)&&a.test(d.overflow+d.overflowY+d.overflowX))return c;return document.body}function F(c,a){c=c.getBoundingClientRect();a=a.getBoundingClientRect();return c.top>a.top&&c.top<a.bottom}
function G(c,a,d,l){let [f]=k.useLexicalComposerContext();z.useEffect(()=>{if(null!=a&&null!=c){let n=f.getRootElement(),r=null!=n?E(n,!1):document.body,w=!1,g=F(a,r),b=function(){w||(window.requestAnimationFrame(function(){d();w=!1}),w=!0);const q=F(a,r);q!==g&&(g=q,null!=l&&l(q))},p=new ResizeObserver(d);window.addEventListener("resize",d);document.addEventListener("scroll",b,{capture:!0,passive:!0});p.observe(a);return()=>{p.unobserve(a);window.removeEventListener("resize",d);document.removeEventListener("scroll",
b,!0)}}},[a,f,l,d,c])}let H=y.createCommand("SCROLL_TYPEAHEAD_OPTION_INTO_VIEW_COMMAND");
function I({close:c,editor:a,anchorElementRef:d,resolution:l,options:f,menuRenderFn:n,onSelectOption:r,shouldSplitNodeWithQuery:w=!1,commandPriority:g=y.COMMAND_PRIORITY_LOW}){let [b,p]=z.useState(null);z.useEffect(()=>{p(0)},[l.match&&l.match.matchingString]);let q=z.useCallback(e=>{a.update(()=>{const m=null!=l.match&&w?D(l.match):null;r(e,m,c,l.match?l.match.matchingString:"")})},[a,w,l.match,r,c]),t=z.useCallback(e=>{const m=a.getRootElement();null!==m&&(m.setAttribute("aria-activedescendant",
"typeahead-item-"+e),p(e))},[a]);z.useEffect(()=>()=>{let e=a.getRootElement();null!==e&&e.removeAttribute("aria-activedescendant")},[a]);A(()=>{null===f?p(null):null===b&&t(0)},[f,b,t]);z.useEffect(()=>v.mergeRegister(a.registerCommand(H,({option:e})=>e.ref&&null!=e.ref.current?(C(e.ref.current),!0):!1,g)),[a,t,g]);z.useEffect(()=>v.mergeRegister(a.registerCommand(y.KEY_ARROW_DOWN_COMMAND,e=>{if(null!==f&&f.length&&null!==b){let m=b!==f.length-1?b+1:0;t(m);let h=f[m];null!=h.ref&&h.ref.current&&
a.dispatchCommand(H,{index:m,option:h});e.preventDefault();e.stopImmediatePropagation()}return!0},g),a.registerCommand(y.KEY_ARROW_UP_COMMAND,e=>{if(null!==f&&f.length&&null!==b){var m=0!==b?b-1:f.length-1;t(m);m=f[m];null!=m.ref&&m.ref.current&&C(m.ref.current);e.preventDefault();e.stopImmediatePropagation()}return!0},g),a.registerCommand(y.KEY_ESCAPE_COMMAND,e=>{e.preventDefault();e.stopImmediatePropagation();c();return!0},g),a.registerCommand(y.KEY_TAB_COMMAND,e=>{if(null===f||null===b||null==
f[b])return!1;e.preventDefault();e.stopImmediatePropagation();q(f[b]);return!0},g),a.registerCommand(y.KEY_ENTER_COMMAND,e=>{if(null===f||null===b||null==f[b])return!1;null!==e&&(e.preventDefault(),e.stopImmediatePropagation());q(f[b]);return!0},g)),[q,c,a,f,b,t,g]);let u=z.useMemo(()=>({options:f,selectOptionAndCleanUp:q,selectedIndex:b,setHighlightedIndex:p}),[q,b,f]);return n(d,u,l.match?l.match.matchingString:"")}
function J(c,a,d,l=document.body){let [f]=k.useLexicalComposerContext(),n=z.useRef(document.createElement("div")),r=z.useCallback(()=>{n.current.style.top=n.current.style.bottom;const g=f.getRootElement(),b=n.current;var p=b.firstChild;if(null!==g&&null!==c){const {left:t,top:u,width:e,height:m}=c.getRect();b.style.top=`${u+window.pageYOffset+n.current.offsetHeight+3}px`;b.style.left=`${t+window.pageXOffset}px`;b.style.height=`${m}px`;b.style.width=`${e}px`;if(null!==p){p.style.top=`${u}`;var q=p.getBoundingClientRect();
p=q.height;q=q.width;const h=g.getBoundingClientRect();t+q>h.right&&(b.style.left=`${h.right-q+window.pageXOffset}px`);(u+p>window.innerHeight||u+p>h.bottom)&&u-h.top>p&&(b.style.top=`${u-p+window.pageYOffset-m}px`)}b.isConnected||(null!=d&&(b.className=d),b.setAttribute("aria-label","Typeahead menu"),b.setAttribute("id","typeahead-menu"),b.setAttribute("role","listbox"),b.style.display="block",b.style.position="absolute",l.append(b));n.current=b;g.setAttribute("aria-controls","typeahead-menu")}},
[f,c,d,l]);z.useEffect(()=>{let g=f.getRootElement();if(null!==c)return r(),()=>{null!==g&&g.removeAttribute("aria-controls");let b=n.current;null!==b&&b.isConnected&&b.remove()}},[f,r,c]);let w=z.useCallback(g=>{null!==c&&(g||a(null))},[c,a]);G(c,n.current,r,w);return n}
exports.LexicalContextMenuPlugin=function({options:c,onClose:a,onOpen:d,onSelectOption:l,menuRenderFn:f,anchorClassName:n,commandPriority:r=y.COMMAND_PRIORITY_LOW,parent:w}){let [g]=k.useLexicalComposerContext(),[b,p]=z.useState(null),q=z.useRef(null);n=J(b,p,n,w);let t=z.useCallback(()=>{p(null);null!=a&&null!==b&&a()},[a,b]),u=z.useCallback(h=>{p(h);null!=d&&null===b&&d(h)},[d,b]),e=z.useCallback(h=>{h.preventDefault();const x=v.calculateZoomLevel(h.target);u({getRect:()=>new DOMRect(h.clientX/
x,h.clientY/x,1,1)})},[u]),m=z.useCallback(h=>{null===b||null==q.current||null==h.target||q.current.contains(h.target)||t()},[t,b]);z.useEffect(()=>{let h=g.getRootElement();if(h)return h.addEventListener("contextmenu",e),()=>h.removeEventListener("contextmenu",e)},[g,e]);z.useEffect(()=>{document.addEventListener("click",m);return()=>document.removeEventListener("click",m)},[g,m]);return null===b||null===g?null:z.createElement(I,{close:t,resolution:b,editor:g,anchorElementRef:n,options:c,menuRenderFn:(h,
x)=>f(h,x,{setMenuRef:K=>{q.current=K}}),onSelectOption:l,commandPriority:r})};exports.MenuOption=B
